//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BozokYemek.Deytabeyz
{
    using System;

    public enum KullaniciTipi : int
    {
        Musteri = 1,
        Admin = 5,
        Kullanici = 3
    }
}
