//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BozokYemek.Deytabeyz
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Manti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manti()
        {
            this.Yorum = new HashSet<Yorum>();
        }

        public int Id { get; set; }
        public string Baslik { get; set; }

        [AllowHtml]
        [UIHint("tinymce_full_compressed")]
        public string Aciklama { get; set; }

        public Nullable<int> KacKisilik { get; set; }
        public Nullable<int> HazirlamaSuresi { get; set; }
        public Nullable<int> PisirmeSuresi { get; set; }

        public string Malzeme { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public Nullable<System.DateTime> DegistirmeTarihi { get; set; }
        public Nullable<bool> Silme { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public string Resim { get; set; }
        public Nullable<int> KullaniciId { get; set; }

        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
