//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BozokYemek.Deytabeyz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int Id { get; set; }
        public string Yazi { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public Nullable<System.DateTime> DegistirmeTarihi { get; set; }
        public Nullable<bool> Silme { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<int> MantiId { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Manti Manti { get; set; }
    }
}
